package com.jackie.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import yyl.yincloud.bean.cityid.CityInfoBean;

import com.jackie.greendao.CityInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityInfoBeanDaoConfig;

    private final CityInfoBeanDao cityInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityInfoBeanDaoConfig = daoConfigMap.get(CityInfoBeanDao.class).clone();
        cityInfoBeanDaoConfig.initIdentityScope(type);

        cityInfoBeanDao = new CityInfoBeanDao(cityInfoBeanDaoConfig, this);

        registerDao(CityInfoBean.class, cityInfoBeanDao);
    }
    
    public void clear() {
        cityInfoBeanDaoConfig.clearIdentityScope();
    }

    public CityInfoBeanDao getCityInfoBeanDao() {
        return cityInfoBeanDao;
    }

}
